#!/bin/sh
set -e

extra_args=
[ ! -d 'source/cyc_core' ] || extra_args='--recurse-submodules source/cyc_core'
dir=$(git rev-parse --absolute-git-dir)
abspath=$(git rev-parse --show-toplevel | sed 's/@/\@/g')
if command -v ctags >/dev/null 2>&1; then
  trap 'rm -f "$dir/$$.tags"' EXIT
  git ls-files $extra_args | sed "s@^@${abspath}/@" | ctags -L - -f "$dir/$$.tags" --extra=+fq --fields=+Sial --c-kinds=+p --c++-kinds=+p
  mv "$dir/$$.tags" "$dir/tags"
fi

if command -v cscope >/dev/null 2>&1; then
  git ls-files $extra_args | sed "s@^@${abspath}/@" | cscope -bq -i - -f "$dir/cscope.out"
fi
